In [1]:
#import required libraries
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
#view feature names of the dataset
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
#view the target of dataset
iris_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
#define features and target objects
X_feature = iris_dataset.data
Y_target = iris_dataset.target

In [5]:
#create object with new values for prediction
X_new = [[3,5,4,1],[5,3,4,2]]

In [6]:
#use the logistic regression estimator
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='liblinear')

In [7]:
#fit data into the logistic regression estimator
logreg.fit (X_feature, Y_target)

LogisticRegression(solver='liblinear')

In [8]:
#predict the outcome using logreg estimator
logreg.predict(X_new)

array([0, 2])

In [9]:
#import library for model persistance
import pickle as pkl

In [10]:
#use dumps method to persist the model
persist_model = pkl.dumps(logreg)
persist_model

b'\x80\x04\x95)\x03\x00\x00\x00\x00\x00\x00\x8c\x1esklearn.linear_model._logistic\x94\x8c\x12LogisticRegression\x94\x93\x94)\x81\x94}\x94(\x8c\x07penalty\x94\x8c\x02l2\x94\x8c\x04dual\x94\x89\x8c\x03tol\x94G?\x1a6\xe2\xeb\x1cC-\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\rfit_intercept\x94\x88\x8c\x11intercept_scaling\x94K\x01\x8c\x0cclass_weight\x94N\x8c\x0crandom_state\x94N\x8c\x06solver\x94\x8c\tliblinear\x94\x8c\x08max_iter\x94Kd\x8c\x0bmulti_class\x94\x8c\x04auto\x94\x8c\x07verbose\x94K\x00\x8c\nwarm_start\x94\x89\x8c\x06n_jobs\x94N\x8c\x08l1_ratio\x94N\x8c\x0en_features_in_\x94K\x04\x8c\x08classes_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x03\x85\x94h\x1c\x8c\x05dtype\x94\x93\x94\x8c\x02i4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x0c\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x94t\x94b\x8c\x05coef_\x94h\

In [11]:
#use joblib.dump to persist the model to a file
import joblib
joblib.dump(logreg,'regresfilename.pkl')

['regresfilename.pkl']

In [14]:
#use joblib.load to persist the model in to a file
#create new estimator from the saved model

new_logreg_estimater= joblib.load('regresfilename.pkl')



In [16]:
#view the new estimator
new_logreg_estimater

LogisticRegression(solver='liblinear')

In [17]:
#validate and use new estimator to predict
new_logreg_estimater.predict(X_new)

array([0, 2])